title: Deep Learning Reading Club
description: AUSMLab - Deep Learning Reading Club

plugins:
  - jekyll-avatar

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
  - netlify.toml

url: 'https://ausmlab.github.io'
baseurl: '/deep-learning-reading-club'

include:
  - assets
  - media
